[package]
name = "squishy"
version = "0.1.8"
edition = "2024"
license = "MIT"
publish = false

[features]
# require manual creation of readonly directory
readonly-test = []

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
