[package]
name = "squishy"
version = "0.1.10"
edition = "2024"
license = "MIT"
publish = false

[features]
# require manual creation of readonly directory
readonly-test = []

[profile.profiling]
inherits = "release"
debug = true

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
