name: Release

on:
  push:
    tags: ['v*']

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: squishy-linux
          path: target/release/squishy

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: squishy-macos
          path: target/release/squishy

  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Rename binaries
        run: |
          mv squishy-linux/squishy squishy-linux-x86_64
          mv squishy-macos/squishy squishy-macos-arm64
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            squishy-linux-x86_64
            squishy-macos-arm64
